apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-pulsar-ext-scaler
  namespace: default
spec:
  selector:
    matchLabels:
      service: keda-pulsar-ext-scaler
  replicas: 1
  template:
    metadata:
      labels:
        service: keda-pulsar-ext-scaler
    spec:
      containers:
      - image: krvarma/pulsar-ext-scaler:latest
        name: scaler
        env:
        - name: EXTERNAL_SCALER_GRPC_PORT
          value: "8091"
---
apiVersion: v1
kind: Service
metadata:
    name: pulsar-ext-scaler-service
    namespace: default
spec:
    selector:
        service: keda-pulsar-ext-scaler
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 8091